controller_manager:
  ros__parameters:
    update_rate: 50
    use_sim_time: true

    diff_cont:
      type: diff_drive_controller/DiffDriveController

    joint_broad:
      type: joint_state_broadcaster/JointStateBroadcaster

diff_cont:
  ros__parameters:
    publish_rate: 50.0
    base_frame_id: body_link
    left_wheel_names: ['wheel2_joint', 'wheel4_joint']
    right_wheel_names: ['wheel1_joint', 'wheel3_joint']
    wheel_separation: 0.37
    wheel_radius: 0.1

    use_stamped_vel: false
